"""add partial index for pending files cleanup

Revision ID: 1303a4a62b28
Revises: 9e1efbb8da06
Create Date: 2026-01-27 16:07:35.030831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1303a4a62b28'
down_revision: Union[str, None] = '9e1efbb8da06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_files_pending_created', 'files', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_pending_created', table_name='files', postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
