"""url into path in media

Revision ID: 141073584803
Revises: d9f8cabe5055
Create Date: 2026-01-06 18:13:28.927161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141073584803'
down_revision: Union[str, None] = 'd9f8cabe5055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('albums_created_by_fkey'), 'albums', type_='foreignkey')
    op.create_foreign_key(None, 'albums', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('media', sa.Column('path', sa.String(length=512), nullable=False, comment='Путь до файла внутри бакета приложения'))
    op.drop_constraint(op.f('media_created_by_fkey'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('media', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment='Ссылка на файл в S3 хранилище'))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_created_by_fkey'), 'media', 'users', ['created_by'], ['id'])
    op.drop_column('media', 'path')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_foreign_key(op.f('albums_created_by_fkey'), 'albums', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
