"""couples table added

Revision ID: 2e53fc6bdddc
Revises: aa39efc53643
Create Date: 2025-12-22 15:07:56.035854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e53fc6bdddc'
down_revision: Union[str, None] = 'aa39efc53643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('partner1_id', sa.Uuid(), nullable=False, comment='UUID первого пользователя пары'),
    sa.Column('partner2_id', sa.Uuid(), nullable=False, comment='UUID второго пользователя пары'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.CheckConstraint('partner1_id <> partner2_id', name='ck_couple_not_self'),
    sa.ForeignKeyConstraint(['partner1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner1_id', 'partner2_id'),
    comment='Сведения о парах, зарегистрированных в приложении'
    )
    op.alter_column('albums', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания записи',
               existing_comment='Дата и время создания записи.',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания записи',
               existing_comment='Дата и время создания записи.',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.drop_constraint(op.f('users_partner_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'partner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=True, comment='UUID пользователя-партнёра'))
    op.create_foreign_key(op.f('users_partner_id_fkey'), 'users', 'users', ['partner_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания записи.',
               existing_comment='Дата и время создания записи',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('albums', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания записи.',
               existing_comment='Дата и время создания записи',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.drop_table('couples')
    # ### end Alembic commands ###
