"""media table added

Revision ID: 3647dab1ac3a
Revises: 2e53fc6bdddc
Create Date: 2025-12-25 16:37:27.270756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3647dab1ac3a'
down_revision: Union[str, None] = '2e53fc6bdddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('url', sa.String(length=512), nullable=False, comment='Ссылка на файл в S3 хранилище'),
    sa.Column('type_', sa.String(length=16), nullable=False, comment='Тип медиа контента'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Наименование медиа файла'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание медиа файла'),
    sa.Column('geo_data', sa.JSON(), nullable=True, comment='Данные о местоположении сохранённого медиа'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='UUID пользователя, загрузившего медиа'),
    sa.Column('album_id', sa.Uuid(), nullable=True, comment='UUID альбома, в который добавлено медиа'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Загруженные пользователями медиа файлы'
    )
    op.alter_column('albums', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment='Уникальный идентификатор записи',
               existing_comment='Уникальный идентификатор альбома',
               existing_nullable=False)
    op.add_column('couples', sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment='Уникальный идентификатор записи',
               existing_comment='Уникальный идентификатор пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Уникальный идентификатор пользователя',
               existing_comment='Уникальный идентификатор записи',
               existing_nullable=False)
    op.drop_column('couples', 'id')
    op.alter_column('albums', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Уникальный идентификатор альбома',
               existing_comment='Уникальный идентификатор записи',
               existing_nullable=False)
    op.drop_table('media')
    # ### end Alembic commands ###
