"""couple members table added

Revision ID: 44d3e30b1b94
Revises: 7f010fca31e9
Create Date: 2026-04-23 20:54:13.676458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44d3e30b1b94'
down_revision: Union[str, None] = '7f010fca31e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_members',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.Column('couple_id', sa.Uuid(), nullable=False, comment='UUID пары'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='UUID пользователя'),
    sa.Column('slot', sa.SmallInteger(), nullable=False, comment='Слот пользователя: 1 или 2'),
    sa.CheckConstraint('slot IN (1, 2)', name='ck_slot_values'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_id', 'slot', name='uq_couple_slot'),
    sa.UniqueConstraint('user_id', name='uq_one_couple_per_user'),
    comment='Таблица с записями о состоящих в парах пользователях'
    )
    op.execute("""
        INSERT INTO couple_members (couple_id, user_id, slot)
        SELECT id, user_low_id, 1 FROM couples
        UNION ALL
        SELECT id, user_high_id, 2 FROM couples
    """)
    op.create_table_comment(
        'album_items',
        'Таблица с записями о сохранённых в альбомах медиа',
        existing_comment='Таблица с записями о сохранённых в альбомах медиа.',
        schema=None
    )
    op.alter_column('albums', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя-владельца ресурса',
               existing_comment='UUID пользователя, создавшего альбом',
               existing_nullable=False)
    op.alter_column('couple_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='couple_request_status'),
               server_default=sa.text("'PENDING'"),
               comment='Статус запроса на создание пары',
               existing_comment='Статус пары между пользователями',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_couple_pair'), 'couples', type_='unique')
    op.drop_constraint(op.f('couples_user_high_id_fkey'), 'couples', type_='foreignkey')
    op.drop_constraint(op.f('couples_user_low_id_fkey'), 'couples', type_='foreignkey')
    op.drop_column('couples', 'user_high_id')
    op.drop_column('couples', 'user_low_id')
    op.alter_column('files', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя-владельца ресурса',
               existing_comment='UUID пользователя, загрузившего медиа',
               existing_nullable=False)
    op.drop_index(op.f('ix_files_pending_created'), table_name='files', postgresql_where="(status = 'PENDING'::file_status)")
    op.alter_column('notes', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя-владельца ресурса',
               existing_comment='UUID пользователя, загрузившего заметку',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Статус пользователя (активный или заблокирован)',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Статус пользователя (активный или заблокирован)',
               existing_nullable=False)
    op.alter_column('notes', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя, загрузившего заметку',
               existing_comment='UUID пользователя-владельца ресурса',
               existing_nullable=False)
    op.create_index(op.f('ix_files_pending_created'), 'files', ['status', 'created_at'], unique=False, postgresql_where="(status = 'PENDING'::file_status)")
    op.alter_column('files', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя, загрузившего медиа',
               existing_comment='UUID пользователя-владельца ресурса',
               existing_nullable=False)
    op.add_column('couples', sa.Column('user_low_id', sa.UUID(), autoincrement=False, nullable=False, comment='Меньший UUID пользователя'))
    op.add_column('couples', sa.Column('user_high_id', sa.UUID(), autoincrement=False, nullable=False, comment='Больший UUID пользователя'))
    op.create_foreign_key(op.f('couples_user_low_id_fkey'), 'couples', 'users', ['user_low_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('couples_user_high_id_fkey'), 'couples', 'users', ['user_high_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_couple_pair'), 'couples', ['user_low_id', 'user_high_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('couple_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='couple_request_status'),
               server_default=None,
               comment='Статус пары между пользователями',
               existing_comment='Статус запроса на создание пары',
               existing_nullable=False)
    op.alter_column('albums', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID пользователя, создавшего альбом',
               existing_comment='UUID пользователя-владельца ресурса',
               existing_nullable=False)
    op.create_table_comment(
        'album_items',
        'Таблица с записями о сохранённых в альбомах медиа.',
        existing_comment='Таблица с записями о сохранённых в альбомах медиа',
        schema=None
    )
    op.execute("""
        UPDATE couples c
        SET
            user_low_id  = cm1.user_id,
            user_high_id = cm2.user_id
        FROM couple_members cm1
        JOIN couple_members cm2
            ON cm1.couple_id = cm2.couple_id
        AND cm2.slot = 2
        WHERE c.id = cm1.couple_id
        AND cm1.slot = 1
    """)
    op.drop_table('couple_members')
    # ### end Alembic commands ###
