"""idempotency keys table removed

Revision ID: 48f5e6ebad13
Revises: ddcb5b60834c
Create Date: 2026-01-17 10:44:09.805350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48f5e6ebad13'
down_revision: Union[str, None] = 'ddcb5b60834c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    op.alter_column('files', 'status',
               existing_type=postgresql.ENUM('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status'),
               server_default=None,
               existing_comment='Текущий статус медиа-файла',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'status',
               existing_type=postgresql.ENUM('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status'),
               server_default=sa.text("'PENDING'::file_status"),
               existing_comment='Текущий статус медиа-файла',
               existing_nullable=False)
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False, comment='Область применения ключа (идиоматично namespace)'),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID записи, относительно которой обеспечивается идемпотентность'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False, comment='Дата и время создания записи'),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_keys_pkey')),
    comment='Ключи для обеспечения идемпотентности'
    )
    # ### end Alembic commands ###
