"""modified comments

Revision ID: 4cf4d77a2e3b
Revises: fc00053c3ca8
Create Date: 2026-03-01 18:29:09.687204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf4d77a2e3b'
down_revision: Union[str, None] = 'fc00053c3ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='Хэш токена обновления (HMAC-SHA256)',
               existing_comment='Хеш токена обновления (Argon2id)',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='Хэш пароля (Argon2id через Passlib)',
               existing_comment='Хеш пароля (Argon2id через Passlib)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='Хеш пароля (Argon2id через Passlib)',
               existing_comment='Хэш пароля (Argon2id через Passlib)',
               existing_nullable=False)
    op.alter_column('user_sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='Хеш токена обновления (Argon2id)',
               existing_comment='Хэш токена обновления (HMAC-SHA256)',
               existing_nullable=False)
    # ### end Alembic commands ###
