"""database init

Revision ID: 6600f29d2b93
Revises: 
Create Date: 2025-12-17 14:37:50.926093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6600f29d2b93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='Уникальный логин (макс. 64 символа)'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Хеш пароля (Argon2id через Passlib)'),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=True, comment='Хеш токена обновления (Argon2id)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус пользователя (активный или заблокирован)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Аутентифицированные пользователи системы'
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_refresh_token_hash'), 'users', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_refresh_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
