"""renamed media_albums to albums

Revision ID: 750559a061c1
Revises: d8ec362834fd
Create Date: 2025-12-19 16:26:26.066707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '750559a061c1'
down_revision: Union[str, None] = 'd8ec362834fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор альбома'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Наименование альбома'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание альбома'),
    sa.Column('cover_url', sa.String(length=512), nullable=True, comment='URL обложки альбома'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='Видимость альбома (личный или публичный)'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='UUID пользователя, создавшего альбом'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи.'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Созданные пользователями альбомы медиа'
    )
    op.create_index(op.f('ix_albums_is_private'), 'albums', ['is_private'], unique=False)
    op.drop_index(op.f('ix_media_albums_is_private'), table_name='media_albums')
    op.drop_table('media_albums')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_albums',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Уникальный идентификатор альбома'),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Наименование альбома'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание альбома'),
    sa.Column('cover_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='URL обложки альбома'),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Видимость альбома (личный или публичный)'),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False, comment='UUID пользователя, создавшего альбом'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False, comment='Дата и время создания записи.'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('media_albums_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('media_albums_pkey')),
    comment='Созданные пользователями альбомы медиа'
    )
    op.create_index(op.f('ix_media_albums_is_private'), 'media_albums', ['is_private'], unique=False)
    op.drop_index(op.f('ix_albums_is_private'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
