"""invariants for couple_requests

Revision ID: 7f010fca31e9
Revises: 4cf4d77a2e3b
Create Date: 2026-04-15 22:20:44.381466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f010fca31e9'
down_revision: Union[str, None] = '4cf4d77a2e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('user_low_id', sa.Uuid(), nullable=False, comment='Меньший UUID пользователя'),
    sa.Column('user_high_id', sa.Uuid(), nullable=False, comment='Больший UUID пользователя'),
    sa.Column('relationship_started_on', sa.Date(), nullable=True, comment='Реальная дата начала отношений'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.CheckConstraint('user_low_id < user_high_id', name='ck_couple_order'),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name='uq_couple_pair'),
    comment='Сведения о зарегистрированных парах между пользователями в приложении'
    )
    op.execute(
        """
        INSERT INTO couples (user_low_id, user_high_id)
        SELECT
            LEAST(initiator_id, recipient_id),
            GREATEST(initiator_id, recipient_id)
        FROM couple_requests
        WHERE status = 'ACCEPTED'
        """
    )
    op.drop_index(op.f('ix_couple_requests_status'), table_name='couple_requests')
    op.create_index('ix_couple_request_initiator_status', 'couple_requests', ['initiator_id'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_couple_request_recipient_status', 'couple_requests', ['recipient_id'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('uq_couple_request_pending', 'couple_requests', [sa.literal_column('LEAST(initiator_id, recipient_id)'), sa.literal_column('GREATEST(initiator_id, recipient_id)')], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table_comment(
        'couple_requests',
        'Сведения о запросах на создание пар между пользователями в приложении',
        existing_comment='Сведения о парах между пользователями в приложении',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'couple_requests',
        'Сведения о парах между пользователями в приложении',
        existing_comment='Сведения о запросах на создание пар между пользователями в приложении',
        schema=None
    )
    op.drop_index('uq_couple_request_pending', table_name='couple_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_couple_request_recipient_status', table_name='couple_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_couple_request_initiator_status', table_name='couple_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_couple_requests_status'), 'couple_requests', ['status'], unique=False)
    op.drop_table('couples')
    # ### end Alembic commands ###
