"""added notes table

Revision ID: 913140dd0a81
Revises: 48f5e6ebad13
Create Date: 2026-01-21 14:30:58.581260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913140dd0a81'
down_revision: Union[str, None] = '48f5e6ebad13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('type', sa.Enum('WISHLIST', 'DREAM', 'GRATITUDE', 'MEMORY', name='note_type'), nullable=False, comment='Тип пользовательской заметки'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Заголовок пользовательской заметки'),
    sa.Column('content', sa.Text(), nullable=True, comment='Содержимое пользовательской заметки'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='UUID пользователя, загрузившего заметку'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользовательские заметки и записки'
    )
    op.create_index(op.f('ix_notes_type'), 'notes', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_type'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
