"""album_items mtm relations table

Revision ID: 9ab5dc45ccac
Revises: 3647dab1ac3a
Create Date: 2025-12-29 11:22:31.643892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab5dc45ccac'
down_revision: Union[str, None] = '3647dab1ac3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_items',
    sa.Column('album_id', sa.Uuid(), nullable=False, comment='UUID медиа альбома'),
    sa.Column('media_id', sa.Uuid(), nullable=False, comment='UUID медиа файла'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'media_id', 'id'),
    comment='Таблица с записями о сохранённых в альбомах медиа.'
    )
    op.drop_constraint(op.f('media_album_id_fkey'), 'media', type_='foreignkey')
    op.drop_column('media', 'album_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=True, comment='UUID альбома, в который добавлено медиа'))
    op.create_foreign_key(op.f('media_album_id_fkey'), 'media', 'albums', ['album_id'], ['id'])
    op.drop_table('album_items')
    # ### end Alembic commands ###
