"""refactor comment on users display_name

Revision ID: 9c859fd8c955
Revises: 56e3842b61c2
Create Date: 2026-07-02 09:58:38.495048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c859fd8c955'
down_revision: Union[str, None] = '56e3842b61c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               comment='Отображаемое имя пользователя (макс. 32 символов)',
               existing_comment='Отображаемое имя пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               comment='Отображаемое имя пользователя',
               existing_comment='Отображаемое имя пользователя (макс. 32 символов)',
               existing_nullable=False)
    # ### end Alembic commands ###
