"""add trigram indexes

Revision ID: 9e1efbb8da06
Revises: 913140dd0a81
Create Date: 2026-01-23 11:42:44.919134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1efbb8da06'
down_revision: Union[str, None] = '913140dd0a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_album_description_trgm', 'albums', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('idx_album_title_trgm', 'albums', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_album_title_trgm', table_name='albums', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_album_description_trgm', table_name='albums', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
