"""media renamed in files

Revision ID: a28895033408
Revises: 141073584803
Create Date: 2026-01-08 18:27:01.129098

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a28895033408'
down_revision: Union[str, None] = '141073584803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('object_key', sa.String(length=512), nullable=False, comment='Путь до файла внутри бакета приложения'),
    sa.Column('type_', sa.String(length=16), nullable=False, comment='Тип медиа файла'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Наименование медиа файла'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание медиа файла'),
    sa.Column('geo_data', sa.JSON(), nullable=True, comment='Данные о местоположении сохранённого медиа'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='UUID пользователя, загрузившего медиа'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Загруженные пользователями медиа файлы'
    )
    op.drop_constraint(op.f('album_items_media_id_fkey'), 'album_items', type_='foreignkey')
    op.drop_column('album_items', 'media_id')
    op.drop_table('media')
    op.add_column('album_items', sa.Column('file_id', sa.Uuid(), nullable=False, comment='UUID медиа файла'))
    op.create_unique_constraint('uq_album_file', 'album_items', ['album_id', 'file_id'])
    op.create_foreign_key(None, 'album_items', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_items', sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID медиа файла'))
    op.drop_constraint(op.f("album_items_file_id_fkey"), 'album_items', type_='foreignkey')
    op.drop_constraint('uq_album_file', 'album_items', type_='unique')
    op.drop_column('album_items', 'file_id')
    op.create_table('media',
    sa.Column('type_', sa.VARCHAR(length=16), autoincrement=False, nullable=False, comment='Тип медиа контента'),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Наименование медиа файла'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание медиа файла'),
    sa.Column('geo_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Данные о местоположении сохранённого медиа'),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False, comment='UUID пользователя, загрузившего медиа'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False, comment='Дата и время создания записи'),
    sa.Column('path', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment='Путь до файла внутри бакета приложения'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('media_created_by_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey')),
    comment='Загруженные пользователями медиа файлы'
    )
    op.create_foreign_key(op.f('album_items_media_id_fkey'), 'album_items', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_table('files')
    # ### end Alembic commands ###
