"""partners one-to-one relations

Revision ID: aa39efc53643
Revises: 750559a061c1
Create Date: 2025-12-22 09:29:52.635728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa39efc53643'
down_revision: Union[str, None] = '750559a061c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('partner_id', sa.Uuid(), nullable=True, comment='UUID пользователя-партнёра'))
    op.create_foreign_key(None, 'users', 'users', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'partner_id')
    # ### end Alembic commands ###
