"""media_albums table added

Revision ID: d8ec362834fd
Revises: 6600f29d2b93
Create Date: 2025-12-19 12:11:56.029630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ec362834fd'
down_revision: Union[str, None] = '6600f29d2b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_albums',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор альбома'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Наименование альбома'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание альбома'),
    sa.Column('cover_url', sa.String(length=512), nullable=True, comment='URL обложки альбома'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='Видимость альбома (личный или публичный)'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='UUID пользователя, создавшего альбом'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи.'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Созданные пользователями альбомы медиа'
    )
    op.create_index(op.f('ix_media_albums_is_private'), 'media_albums', ['is_private'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='URL аватара пользователя'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_media_albums_is_private'), table_name='media_albums')
    op.drop_table('media_albums')
    # ### end Alembic commands ###
