"""couples request accept system

Revision ID: d9f8cabe5055
Revises: 9ab5dc45ccac
Create Date: 2025-12-29 13:21:19.747092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f8cabe5055'
down_revision: Union[str, None] = '9ab5dc45ccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_requests',
    sa.Column('initiator_id', sa.Uuid(), nullable=False, comment='UUID пользователя-инициатора'),
    sa.Column('recipient_id', sa.Uuid(), nullable=False, comment='UUID пользователя-реципиента'),
    sa.Column('status', sa.String(length=8), nullable=False, comment='Статус пары между пользователями'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время принятия приглашения'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.CheckConstraint('initiator_id <> recipient_id', name='ck_couple_not_self'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('initiator_id', 'recipient_id', 'id'),
    comment='Сведения о парах между пользователями в приложении'
    )
    op.create_index(op.f('ix_couple_requests_status'), 'couple_requests', ['status'], unique=False)
    op.drop_table('couples')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('partner1_id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID первого пользователя пары'),
    sa.Column('partner2_id', sa.UUID(), autoincrement=False, nullable=False, comment='UUID второго пользователя пары'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False, comment='Дата и время создания записи'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Уникальный идентификатор записи'),
    sa.CheckConstraint('partner1_id <> partner2_id', name=op.f('ck_couple_not_self')),
    sa.ForeignKeyConstraint(['partner1_id'], ['users.id'], name=op.f('couples_partner1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner2_id'], ['users.id'], name=op.f('couples_partner2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner1_id', 'partner2_id', name=op.f('couples_pkey')),
    comment='Сведения о парах, зарегистрированных в приложении'
    )
    op.drop_index(op.f('ix_couple_requests_status'), table_name='couple_requests')
    op.drop_table('couple_requests')
    # ### end Alembic commands ###
