"""files idempotency and status enums

Revision ID: ddcb5b60834c
Revises: a28895033408
Create Date: 2026-01-09 15:33:55.776465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcb5b60834c'
down_revision: Union[str, None] = 'a28895033408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.Text(), nullable=False, comment='Область применения ключа (идиоматично namespace)'),
    sa.Column('entity_id', sa.Uuid(), nullable=False, comment='UUID записи, относительно которой обеспечивается идемпотентность'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ключи для обеспечения идемпотентности'
    )
    couple_request_status = sa.Enum("PENDING", "ACCEPTED", "DECLINED", "EXPIRED", name="couple_request_status")
    couple_request_status.create(op.get_bind())
    op.alter_column('couple_requests', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=couple_request_status,
               existing_comment='Статус пары между пользователями',
               existing_nullable=False,
               postgresql_using="status::couple_request_status")
    op.alter_column("files", "type_",
               new_column_name="content_type",
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_comment='Тип медиа файла',
               existing_nullable=False,)
    file_status = sa.Enum('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status')
    file_status.create(op.get_bind())
    op.add_column('files', sa.Column('status', file_status, nullable=False, comment='Текущий статус медиа-файла', server_default="PENDING"))
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', "content_type",
               new_column_name="type_",
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_comment='Тип медиа файла')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    file_status = sa.Enum('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status')
    op.drop_column('files', 'status')
    file_status.drop(op.get_bind(), checkfirst=True)
    couple_request_status = sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='couple_request_status')
    op.alter_column('couple_requests', 'status',
               existing_type=couple_request_status,
               type_=sa.VARCHAR(length=8),
               existing_comment='Статус пары между пользователями',
               existing_nullable=False)
    couple_request_status.drop(op.get_bind(), checkfirst=True)
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
