"""naming refactoring

Revision ID: ec7dac4fccee
Revises: 44d3e30b1b94
Create Date: 2026-06-18 21:00:57.745071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec7dac4fccee'
down_revision: Union[str, None] = '44d3e30b1b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album_items', 'album_id',
               existing_type=sa.UUID(),
               comment='UUID медиаальбома',
               existing_comment='UUID медиа альбома',
               existing_nullable=False)
    op.alter_column('album_items', 'file_id',
               existing_type=sa.UUID(),
               comment='UUID медиафайла',
               existing_comment='UUID медиа файла',
               existing_nullable=False)
    op.alter_column('files', 'content_type',
               existing_type=sa.VARCHAR(length=64),
               comment='Тип медиафайла',
               existing_comment='Тип медиа файла',
               existing_nullable=False)
    op.alter_column('files', 'status',
               existing_type=postgresql.ENUM('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status'),
               comment='Текущий статус медиафайла',
               existing_comment='Текущий статус медиа-файла',
               existing_nullable=False)
    op.alter_column('files', 'title',
               existing_type=sa.VARCHAR(length=64),
               comment='Наименование медиафайла',
               existing_comment='Наименование медиа файла',
               existing_nullable=False)
    op.alter_column('files', 'description',
               existing_type=sa.TEXT(),
               comment='Описание медиафайла',
               existing_comment='Описание медиа файла',
               existing_nullable=True)
    op.create_table_comment(
        'files',
        'Загруженные пользователями медиафайлы',
        existing_comment='Загруженные пользователями медиа файлы',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'files',
        'Загруженные пользователями медиа файлы',
        existing_comment='Загруженные пользователями медиафайлы',
        schema=None
    )
    op.alter_column('files', 'description',
               existing_type=sa.TEXT(),
               comment='Описание медиа файла',
               existing_comment='Описание медиафайла',
               existing_nullable=True)
    op.alter_column('files', 'title',
               existing_type=sa.VARCHAR(length=64),
               comment='Наименование медиа файла',
               existing_comment='Наименование медиафайла',
               existing_nullable=False)
    op.alter_column('files', 'status',
               existing_type=postgresql.ENUM('PENDING', 'UPLOADED', 'FAILED', 'DELETED', name='file_status'),
               comment='Текущий статус медиа-файла',
               existing_comment='Текущий статус медиафайла',
               existing_nullable=False)
    op.alter_column('files', 'content_type',
               existing_type=sa.VARCHAR(length=64),
               comment='Тип медиа файла',
               existing_comment='Тип медиафайла',
               existing_nullable=False)
    op.alter_column('album_items', 'file_id',
               existing_type=sa.UUID(),
               comment='UUID медиа файла',
               existing_comment='UUID медиафайла',
               existing_nullable=False)
    op.alter_column('album_items', 'album_id',
               existing_type=sa.UUID(),
               comment='UUID медиа альбома',
               existing_comment='UUID медиаальбома',
               existing_nullable=False)
    # ### end Alembic commands ###
