"""added user sessions

Revision ID: fc00053c3ca8
Revises: 1303a4a62b28
Create Date: 2026-02-21 17:29:15.966426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc00053c3ca8'
down_revision: Union[str, None] = '1303a4a62b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False, comment='Хеш токена обновления (Argon2id)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время, когда токен будет просрочен'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления сессии'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Информация о пользовательских сессиях'
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.drop_index(op.f('ix_users_refresh_token_hash'), table_name='users')
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True, comment='Хеш токена обновления (Argon2id)'))
    op.create_index(op.f('ix_users_refresh_token_hash'), 'users', ['refresh_token_hash'], unique=False)
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
